name: Update Profile Badges

on:
  schedule:
    - cron: '0 0 * * *'  # Diario
  workflow_dispatch:

jobs:
  update-badges:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate Badges
        uses: bledxs/soff-telemetry@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          theme: 'dark'
          service: 'all'
          output_dir: './data'

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "ðŸ¤– Update badges" || exit 0
          git push
